In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("insurance_claims_fraud_10000.csv")

In [3]:
df.head()

,claim_id,policyholder_id,claim_amount,claim_date,claim_location,provider_id,claim_type,submission_channel,is_fraudulent
0,CLM00005081,POL001120,3324.49,2024-07-07 12:00:00,"Dubai, UAE",PRV00524,auto,mobile app,0
1,CLM00000565,POL003569,241.85,2024-02-19 12:00:00,"Sao Paulo, Brazil",PRV00096,health,online,0
2,CLM00007370,POL001936,505.90,2024-07-02 17:00:00,"Cape Town, South Africa",PRV00286,life,mobile app,0
3,CLM00005151,POL003251,100.79,2024-01-15 15:00:00,"Mumbai, India",PRV00732,travel,online,0
4,CLM00009791,POL002317,1006.56,2024-05-25 13:00:00,"Cape Town, South Africa",PRV00279,vision,online,0

In [4]:
df.isnull().sum()

claim_id                0
policyholder_id       320
claim_amount          110
claim_date            210
claim_location        480
provider_id             0
claim_type              0
submission_channel    260
is_fraudulent           0
dtype: int64

In [5]:
df.shape

(10015, 9)

In [6]:
correlation = df.corr(numeric_only=True)

print(correlation)

fraud_by_location = df.groupby("claim_location")["is_fraudulent"].mean()

print(fraud_by_location)

               claim_amount  is_fraudulent
claim_amount       1.000000       0.039784
is_fraudulent      0.039784       1.000000
claim_location
Cape Town, South Africa    0.009298
Chicago, USA               0.010183
Delhi, India               0.012358
Dubai, UAE                 0.007431
Manchester, UK             0.012862
Mumbai, India              0.023983
Sao Paulo, Brazil          0.015674
Singapore                  0.015823
Sydney, Australia          0.011411
Toronto, Canada            0.023052
Name: is_fraudulent, dtype: float64

In [7]:
df['policyholder_id'] = df['policyholder_id'].fillna('Unknown').replace('', 'Unknown')
df["claim_amount"] = df["claim_amount"].fillna(df["claim_amount"].mean)

In [8]:
#handle missing values

df["claim_date"] = pd.to_datetime(df["claim_date"], errors="coerce")
df["claim_date"] = df["claim_date"].ffill()
df["claim_location"] = df["claim_location"].fillna("Unknown")
df["submission_channel"] = df["submission_channel"].fillna("Unknown")
df.isnull().sum()

claim_id              0
policyholder_id       0
claim_amount          0
claim_date            0
claim_location        0
provider_id           0
claim_type            0
submission_channel    0
is_fraudulent         0
dtype: int64

In [9]:
df.describe()

                          claim_date  is_fraudulent
count                          10015   10015.000000
mean   2024-04-27 18:53:25.671492864       0.014378
min              2024-01-01 00:00:00       0.000000
25%              2024-02-27 04:00:00       0.000000
50%              2024-04-26 00:00:00       0.000000
75%              2024-06-27 05:00:00       0.000000
max              2024-08-27 23:00:00       1.000000
std                              NaN       0.119051

In [10]:
df.duplicated().sum()

np.int64(15)

In [11]:
df = df.drop_duplicates()

In [12]:
df.head()

,claim_id,policyholder_id,claim_amount,claim_date,claim_location,provider_id,claim_type,submission_channel,is_fraudulent
0,CLM00005081,POL001120,3324.49,2024-07-07 12:00:00,"Dubai, UAE",PRV00524,auto,mobile app,0
1,CLM00000565,POL003569,241.85,2024-02-19 12:00:00,"Sao Paulo, Brazil",PRV00096,health,online,0
2,CLM00007370,POL001936,505.9,2024-07-02 17:00:00,"Cape Town, South Africa",PRV00286,life,mobile app,0
3,CLM00005151,POL003251,100.79,2024-01-15 15:00:00,"Mumbai, India",PRV00732,travel,online,0
4,CLM00009791,POL002317,1006.56,2024-05-25 13:00:00,"Cape Town, South Africa",PRV00279,vision,online,0

# Feature Engineering

In [13]:
df["claim_year"] = df["claim_date"].dt.year
df["claim_month"] = df["claim_date"].dt.month
df["claim_day"] = df["claim_date"].dt.day
df["claim_dayofweek"] = df["claim_date"].dt.dayofweek